name: Crowdin Cleanup

# **What it does**: Homogenizes localized non-translatable frontmatter after every push by the octoglot bot to the translations branch.
# **Why we have it**: So Crowdin doesn't break frontmatter in production.
# **Who does it impact**: Docs engineering and international expansion.

on:
  workflow_dispatch:
  push:
    branches:
      - translations

jobs:
  homogenize_frontmatter:
    name: Homogenize frontmatter
    # Only run this after octoglot commits or when a Hubber is running this using the workflow dispatch button.
    if: github.repository == 'github/docs-internal' && (github.event.pusher.name == 'octoglot' || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97

      - name: Setup Node
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Homogenize frontmatter
        run: script/i18n/homogenize-frontmatter.js

      - name: Check in homogenized files
        uses: EndBug/add-and-commit@998652d28d7702d095d40f52ae42982a80ae8c7d
        with:
          # The arguments for the `git add` command
          add: 'translations'

          # The message for the commit
          message: 'Run script/i18n/homogenize-frontmatter.js'

        env:
          # Disable pre-commit hooks; they don't play nicely with add-and-commit
          HUSKY: '0'
